### ISSUE TITLE
Beginner

### ISSUE THREAD

**Issue by semajoel** [billthefarmer/scope#14]
Hi,  thanx for the great work. Am not that we'll versed with android app, am have gotten your code, imported it in eclipse. It won't run, there is 
A couple of error, 
- invalid resource directory name, drawable-xxxhdpi.
- error generating final archive:

Will be glad to get some help on these.

**Comment by billthefarmer** [comment]
You can delete the drawable-xxxhdpi directory if eclipse doesn't like it. It's there to support hi rez devices. The gradle build system complains if it's missing. I stopped using eclipse a long time ago. I don't know about the error unless it's because of the directory .

It's a good idea to read the [android docs](https://developer.android.com/guide/index.html) and start with something simple if you are a beginner. The best place to ask questions is probably [Stack Overflow](https://stackoverflow.com/).

**Comment by semajoel** [comment]
What tool would you recommend but eclipse?

**Comment by billthefarmer** [comment]
[The Official IDE for Android](https://developer.android.com/studio/index.html). They stopped supporting eclipse several years ago.
