### ISSUE TITLE
Often crashes when switching to the frequency domain (spectrum) view

### ISSUE THREAD

**Issue by Olf0** [billthefarmer/scope#16]
Oscilloscope 1.14 crashes often (but not always), when switching to the frequency domain (spectrum) view.
Logs of one such crash (under AOSP 4.1.2):
- Main-log (filtered for "billthefarmer"): [alogcat-mainlog_org.billthefarmer.scope_crashes-when-switching-to-spectrum.txt](https://github.com/billthefarmer/scope/files/1545704/alogcat-mainlog_org.billthefarmer.scope_crashes-when-switching-to-spectrum.txt)
- Event-log (filtered for "billthefarmer"): [alogcat-eventlog_org.billthefarmer.scope_crashes-when-switching-to-spectrum.txt](https://github.com/billthefarmer/scope/files/1545705/alogcat-eventlog_org.billthefarmer.scope_crashes-when-switching-to-spectrum.txt)

**Comment by billthefarmer** [comment]
The section of code that crashed was donated as an enhancement to close the audio system down cleanly when pausing. I don't think there is anything wrong with it, I think this crash is due to an occasional overlap or race between the scope shutting down the audio and the spectrum starting it up again. It doesn't happen on later versions of android, I think. I will update the code to trap the exception so it doesn't cause a crash.

**Comment by Olf0** [comment]
Thanks for commit [#d289f39](https://github.com/billthefarmer/scope/commit/d289f392dd01a94bdc7fcc746c4fcf9702a48f2f).
I will report, if this has fixed the issuebon my device, when I can get hold of an updated version of "Oscilloscope" to install and test it.

**Comment by Olf0** [comment]
Fixed in Oscilloscope 1.1.5 (obtained from F-Droid).
Thank you, @billthefarmer, this was a nice, little Christmas present.
All the best and an excellent start into the new year!
