### ISSUE TITLE
Spectrum features to practice singing

### ISSUE THREAD

**Issue by andreasbuhr** [billthefarmer/scope#17]
Dear Bill,

I like using your scope app to practice singing. Thank you very much for writing it and sharing it. I like its simplicity and of coarse that it is open source. There are a few features that I'd like to have. I am doing programming for a living, so maybe I could implement these features with a little help from your side.

It would be great if:

1. One could select the maximum and the minimum frequency in the spectrum. For example, I do only need the range from 80Hz to ca. 500Hz and it would be great if that was configurable.
2. One could select the time window for the FFT. At the moment it is pretty short. This leads to the effect that low frequencies always appear as having a quite broad spectrum. It's hard to see whether I correctly sing notes below 100Hz.
3. The marker always selects the maximum in the spectrum. However, often the overtones have a higher amplitude than the tone I try to sing. For example I try to sing C3 (130.8 Hz), and the marker marks the first overtone at about 262 Hz. So when practising, I am calculating in my head what the correct frequency for the overtones is to check the marker value. I'd like to have an algorithm which finds multiple maxima and marks them all.
4. Finally it would be great I could say: I want to sing in e.g. E-major and then the corresponding frequencies are marked with a line or similar.

I also tried your "tuner" app, but I cannot really use it for singing. It's probably fine to tune instruments, but for tracking what I am singing somehow the spectrum reacts too slow, the text display reacts too fast and somehow it needs too much brainpower to interpret its display. I like the spectrum of your oscilloscope app much better.

Probably I could implement the features mentioned above, once I am up and running with your source code. However, I failed building it. I am not an app developer and I do not know the usual tools there. What is the intended build procedure? I tried executing the "gradlew" script, which gives me the following error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'scope'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.2.2)
      > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.2.2/gradle-core-2.2.2.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.2.2/gradle-core-2.2.2.jar'.
            > sun.security.validator.ValidatorException: No trusted certificate found
```

I would appreciate your help very much.
best
Andreas

**Comment by billthefarmer** [comment]
That's a fairly major design change. You would probably be better off taking the [SpectrumActivity](https://github.com/billthefarmer/scope/blob/master/src/main/java/org/billthefarmer/scope/SpectrumActivity.java), Spectrum, Scale, FrequencyScale java source files and the relevant XML files and building your own app. The reason the spectrum goes so fast is because I'm using the default sample rate which is usually 44100. Because you need a restricted frequency range you could reduce that to 11025 which will slow things down. See the code in my [Tuner](https://github.com/billthefarmer/tuner/blob/d80ef4f82aa500b18bf1206b1958cc22e9ddbb6d/src/main/java/org/billthefarmer/tuner/MainActivity.java#L694) app to do that and make sure it's working. Also see code in the Tuner app for filtering and downsampling to attempt to solve a similar problem.

The build error you are getting is a network problem and happens sometimes. You just have to try again. The approved android build system is [Android Studio](https://developer.android.com/studio/index.html). I don't use it, but it will import my code so you can.
