### ISSUE TITLE
Second input wave

### ISSUE THREAD

**Issue by brauer-t** [billthefarmer/scope#29]
Hello,

Thank you for this great app. Do you think it would be possible to add a second input wave ? (Using an usb module to conncet to the device)

Have a nice day,

Tom

**Comment by billthefarmer** [comment]
I have looked this up, USB headsets work, but only for listening, not for the microphone. Bluetooth headsets appear to work, so if you can get a Bluetooth audio device that looks like a headset it should work. I haven't made this app dual channel because there's no stereo mic or audio input on android devices.
