### ISSUE TITLE
Intuitive Touchscreen Guestures

### ISSUE THREAD

**Issue by RageGamerBoi** [billthefarmer/scope#34]
I have a few gestures that I would love to have added:
1. Pinch vertically to scale. This would make it much easier to read smaller waves that the microphone doesn't pick up well.
2. Pinch horizontally to adjust timescale. This would be very nice to have as well to easily navigate the timescale setting.
3. A button to switch between moving the yellow index line and the ability to drag in any direction to adjust position.

In effect it would navigate a bit like Google Maps and make it a lot more intuitive for touchscreen use of the major analog controls on an oscilloscope:

![image](https://user-images.githubusercontent.com/105567407/232949569-0819e853-78ae-4708-b316-6f67918122ed.png)

There could be toggles to disable each gesture in settings for if one prefers not to use them as well.

**Comment by billthefarmer** [comment]
There is no point in a gain control because there is generally no usable audio input other than the microphone on android devices and there are two lots of AGC, in the audio system and in the app. Increasing the gain would just amplify the noise. To pick signals out of the noise, use the spectrum.

I will investigate using gesture detectors for changing the timebase and scrolling. There is no need for a button as the detectors can discriminate between different gestures, such as tap, scroll and pinch.

**Comment by RageGamerBoi** [comment]
The reason I would like gain control is because the AGC on my device is practically non-existant (for some odd reason) and a lot of things end up being rather quiet.
It's up to you though ;)

Thanks for looking into it! :heart:

**Comment by billthefarmer** [comment]
I have increased the maximum gain. I can't increase it any more because the audio input on tablets tends to be more sensitive and noisy and would fill the display.

I have added scroll, fling and scale gestures. The index line now only responds to a definite single tap as the detector has to discriminate from the other possible gestures. This will be in the next version.

**Comment by RageGamerBoi** [comment]
> I can't increase it any more because the audio input on tablets tends to be more sensitive and noisy and would fill the display.

That's why we need adjustable gain, so those who aren't on tablets or who are measuring 
 
> I have added scroll, fling and scale gestures. The index line now only responds to a definite single tap as the detector has to discriminate from the other possible gestures. This will be in the next version.

**Comment by RageGamerBoi** [comment]
Oh, no, I just want to zoom in slightly because the mic on my phone is not that sensitive (AGC doesn't fix it).
Most users won't use it, but for me at least, it is worth the tradeoff of extra noise.
Maybe a toggle in settings that's disabled by default.

It's your choice as to whether or not you implement it ofc, I just wanted to explain why I think it's a good feature.
Sorry for my slightly incoherent descriptions...
